{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "cathedral-firmware",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[0.000e+00 7.400e+01 6.000e+01 ... 4.000e+00 3.100e+01 4.600e-01]\n",
      " [1.000e+00 5.600e+01 4.800e+01 ... 6.000e+00 2.500e+01 0.000e+00]\n",
      " [2.000e+00 5.800e+01 4.500e+01 ... 3.000e+00 1.200e+01 0.000e+00]\n",
      " ...\n",
      " [1.316e+03 1.070e+02 9.200e+01 ... 4.000e+00 1.700e+01 0.000e+00]\n",
      " [1.317e+03 1.060e+02 9.300e+01 ... 4.000e+00 2.000e+01 0.000e+00]\n",
      " [1.318e+03 9.900e+01 8.800e+01 ... 4.000e+00 2.000e+01 0.000e+00]]\n",
      "[[ 74.  60.  45. ...   7.   2.  20.]\n",
      " [ 56.  48.  39. ...  10.   5.  16.]\n",
      " [ 58.  45.  32. ...  10.  10.   8.]\n",
      " ...\n",
      " [107.  92.  77. ...  10.  10.  12.]\n",
      " [106.  93.  79. ...  10.  10.  13.]\n",
      " [ 99.  88.  77. ...  10.  10.  12.]]\n",
      "[31. 25. 12. ... 17. 20. 20.]\n",
      "Epoch 1/50\n",
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_74 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_75 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_76 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n",
      "Epoch 1/50\n",
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_77 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_78 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_79 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n",
      "Epoch 1/50\n",
      "Epoch 1/50\n",
      "Epoch 1/50\n",
      "Epoch 1/50\n",
      "Larger: nan (nan) MSE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_80 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_81 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_82 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n",
      "/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py\", line 163, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py\", line 1158, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/toto/project_1/project_1/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:830 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:813 run_step  *\n",
      "        outputs = model.train_step(data)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/training.py:770 train_step  *\n",
      "        y_pred = self(x, training=True)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/base_layer.py:989 __call__  *\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    /home/toto/project_1/project_1/lib/python3.6/site-packages/keras/engine/input_spec.py:248 assert_input_compatibility  *\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_83 is incompatible with the layer: expected axis -1 of input shape to have value 15 but received input with shape (None, 14)\n",
      "\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "# Regression Example With Boston Dataset: Standardized and Larger\n",
    "from pandas import read_csv\n",
    "import pandas as pd\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.wrappers.scikit_learn import KerasRegressor\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "# load dataset\n",
    "#dataframe = read_csv(\"housing.csv\",delim_whitespace=True, header=None)\n",
    "dataframe = read_csv(\"weather_coma_delimiter.csv\",delim_whitespace=True, header=None)\n",
    "\n",
    "dataset = dataframe.values\n",
    "print(dataset)\n",
    "# split into input (X) and output (Y) variables\n",
    "X = dataset[:,1:16]\n",
    "print(X)\n",
    "Y = dataset[:,16]\n",
    "print(Y)\n",
    "# define the model\n",
    "def larger_model():\n",
    "\t# create model\n",
    "\tmodel = Sequential()\n",
    "\tmodel.add(Dense(13, input_dim=15, kernel_initializer='normal', activation='relu'))\n",
    "\tmodel.add(Dense(6, kernel_initializer='normal', activation='relu'))\n",
    "\tmodel.add(Dense(1, kernel_initializer='normal'))\n",
    "\t# Compile model\n",
    "\tmodel.compile(loss='mean_squared_error', optimizer='adam')\n",
    "\treturn model\n",
    "# evaluate model with standardized dataset\n",
    "estimators = []\n",
    "estimators.append(('standardize', StandardScaler()))\n",
    "estimators.append(('mlp', KerasRegressor(build_fn=larger_model, epochs=50, batch_size=5, verbose=1)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = KFold(n_splits=10)\n",
    "results = cross_val_score(pipeline, X, Y, cv=kfold)\n",
    "print(\"Larger: %.2f (%.2f) MSE\" % (results.mean(), results.std()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "abstract-hampshire",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow\n",
      "  Downloading tensorflow-2.5.0-cp36-cp36m-manylinux2010_x86_64.whl (454.3 MB)\n",
      "\u001b[K     |████████████████████████████████| 454.3 MB 7.4 kB/s eta 0:00:01     |████████████████▊               | 237.9 MB 3.4 MB/s eta 0:01:05\n",
      "\u001b[?25hCollecting grpcio~=1.34.0\n",
      "  Downloading grpcio-1.34.1-cp36-cp36m-manylinux2014_x86_64.whl (4.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.0 MB 4.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting termcolor~=1.1.0\n",
      "  Downloading termcolor-1.1.0.tar.gz (3.9 kB)\n",
      "Collecting google-pasta~=0.2\n",
      "  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "\u001b[K     |████████████████████████████████| 57 kB 1.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: wheel~=0.35 in ./project_1/lib/python3.6/site-packages (from tensorflow) (0.36.2)\n",
      "Collecting flatbuffers~=1.12.0\n",
      "  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)\n",
      "Collecting wrapt~=1.12.1\n",
      "  Downloading wrapt-1.12.1.tar.gz (27 kB)\n",
      "Requirement already satisfied: h5py~=3.1.0 in ./project_1/lib/python3.6/site-packages (from tensorflow) (3.1.0)\n",
      "Collecting absl-py~=0.10\n",
      "  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)\n",
      "\u001b[K     |████████████████████████████████| 132 kB 4.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting opt-einsum~=3.3.0\n",
      "  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
      "\u001b[K     |████████████████████████████████| 65 kB 1.7 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: numpy~=1.19.2 in ./project_1/lib/python3.6/site-packages (from tensorflow) (1.19.5)\n",
      "Collecting tensorboard~=2.5\n",
      "  Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 6.0 MB 3.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting keras-nightly~=2.5.0.dev\n",
      "  Downloading keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.2 MB 3.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: six~=1.15.0 in ./project_1/lib/python3.6/site-packages (from tensorflow) (1.15.0)\n",
      "Collecting astunparse~=1.6.3\n",
      "  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Collecting protobuf>=3.9.2\n",
      "  Downloading protobuf-3.17.3-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.0 MB 4.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting gast==0.4.0\n",
      "  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)\n",
      "Collecting keras-preprocessing~=1.1.2\n",
      "  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)\n",
      "\u001b[K     |████████████████████████████████| 42 kB 921 kB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: typing-extensions~=3.7.4 in ./project_1/lib/python3.6/site-packages (from tensorflow) (3.7.4.3)\n",
      "Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0\n",
      "  Downloading tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)\n",
      "\u001b[K     |████████████████████████████████| 462 kB 4.6 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: cached-property in ./project_1/lib/python3.6/site-packages (from h5py~=3.1.0->tensorflow) (1.5.2)\n",
      "Collecting werkzeug>=0.11.15\n",
      "  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)\n",
      "\u001b[K     |████████████████████████████████| 288 kB 1.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting google-auth<2,>=1.6.3\n",
      "  Downloading google_auth-1.31.0-py2.py3-none-any.whl (147 kB)\n",
      "\u001b[K     |████████████████████████████████| 147 kB 3.4 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting tensorboard-data-server<0.7.0,>=0.6.0\n",
      "  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.9 MB 744 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting markdown>=2.6.8\n",
      "  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)\n",
      "\u001b[K     |████████████████████████████████| 97 kB 668 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting requests<3,>=2.21.0\n",
      "  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)\n",
      "\u001b[K     |████████████████████████████████| 61 kB 1.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting tensorboard-plugin-wit>=1.6.0\n",
      "  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)\n",
      "\u001b[K     |████████████████████████████████| 781 kB 4.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting google-auth-oauthlib<0.5,>=0.4.1\n",
      "  Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)\n",
      "Requirement already satisfied: setuptools>=41.0.0 in ./project_1/lib/python3.6/site-packages (from tensorboard~=2.5->tensorflow) (53.0.0)\n",
      "Collecting cachetools<5.0,>=2.0.0\n",
      "  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)\n",
      "Collecting rsa<5,>=3.1.4\n",
      "  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)\n",
      "Collecting pyasn1-modules>=0.2.1\n",
      "  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\n",
      "\u001b[K     |████████████████████████████████| 155 kB 2.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting requests-oauthlib>=0.7.0\n",
      "  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: importlib-metadata in ./project_1/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard~=2.5->tensorflow) (3.4.0)\n",
      "Collecting pyasn1<0.5.0,>=0.4.6\n",
      "  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)\n",
      "\u001b[K     |████████████████████████████████| 77 kB 2.9 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: urllib3<1.27,>=1.21.1 in ./project_1/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (1.26.3)\n",
      "Collecting chardet<5,>=3.0.2\n",
      "  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)\n",
      "\u001b[K     |████████████████████████████████| 178 kB 5.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting certifi>=2017.4.17\n",
      "  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)\n",
      "\u001b[K     |████████████████████████████████| 145 kB 5.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting idna<3,>=2.5\n",
      "  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\n",
      "\u001b[K     |████████████████████████████████| 58 kB 3.7 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting oauthlib>=3.0.0\n",
      "  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)\n",
      "\u001b[K     |████████████████████████████████| 146 kB 5.7 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting dataclasses\n",
      "  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)\n",
      "Requirement already satisfied: zipp>=0.5 in ./project_1/lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard~=2.5->tensorflow) (3.4.0)\n",
      "Building wheels for collected packages: termcolor, wrapt\n",
      "  Building wheel for termcolor (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=a8272ab8e293b61de74278bd63e9a6d21b8eb1730e2c28318fe95531862283e4\n",
      "  Stored in directory: /home/toto/.cache/pip/wheels/93/2a/eb/e58dbcbc963549ee4f065ff80a59f274cc7210b6eab962acdc\n",
      "  Building wheel for wrapt (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for wrapt: filename=wrapt-1.12.1-cp36-cp36m-linux_x86_64.whl size=67527 sha256=9189f2d45e0b8c324061c56e03f1586d3043e66fa16d1ace75ebc419bcdb6340\n",
      "  Stored in directory: /home/toto/.cache/pip/wheels/32/42/7f/23cae9ff6ef66798d00dc5d659088e57dbba01566f6c60db63\n",
      "Successfully built termcolor wrapt\n",
      "Installing collected packages: pyasn1, idna, chardet, certifi, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, dataclasses, werkzeug, tensorboard-plugin-wit, tensorboard-data-server, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-nightly, google-pasta, gast, flatbuffers, astunparse, tensorflow\n",
      "Successfully installed absl-py-0.13.0 astunparse-1.6.3 cachetools-4.2.2 certifi-2021.5.30 chardet-4.0.0 dataclasses-0.8 flatbuffers-1.12 gast-0.4.0 google-auth-1.31.0 google-auth-oauthlib-0.4.4 google-pasta-0.2.0 grpcio-1.34.1 idna-2.10 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 markdown-3.3.4 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.25.1 requests-oauthlib-1.3.0 rsa-4.7.2 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.5.0 tensorflow-estimator-2.5.0 termcolor-1.1.0 werkzeug-2.0.1 wrapt-1.12.1\n",
      "\u001b[33mWARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.\n",
      "You should consider upgrading via the '/home/toto/project_1/project_1/bin/python -m pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install tensorflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "greater-copper",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting keras\n",
      "  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)\n",
      "Requirement already satisfied: numpy>=1.9.1 in ./project_1/lib/python3.6/site-packages (from keras) (1.19.5)\n",
      "Collecting h5py\n",
      "  Downloading h5py-3.1.0-cp36-cp36m-manylinux1_x86_64.whl (4.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.0 MB 1.5 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: scipy>=0.14 in ./project_1/lib/python3.6/site-packages (from keras) (1.5.4)\n",
      "Collecting pyyaml\n",
      "  Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)\n",
      "\u001b[K     |████████████████████████████████| 640 kB 3.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting cached-property\n",
      "  Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)\n",
      "Installing collected packages: cached-property, pyyaml, h5py, keras\n",
      "Successfully installed cached-property-1.5.2 h5py-3.1.0 keras-2.4.3 pyyaml-5.4.1\n",
      "\u001b[33mWARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.\n",
      "You should consider upgrading via the '/home/toto/project_1/project_1/bin/python -m pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install keras\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "private-validity",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
